# Spring properties
spring:
  application:
    name: prodect_hazelcast  # Service registers under this name
    datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;Mode=Oracle
      username: sa
      password:
      driverClassName : org.h2.Driver
      continue-on-error: false
      validation-query: select 1;
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mapping: true
        dialect: org.hibernate.dialect.H2Dialect
